baseurl = "/"
languageCode = "en-us"
title = "Stan for cognitive science"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"
[permalinks]
    post = "/:year/:month/:day/:slug/"

    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 2
    [[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 2
    [[menu.main]]
    name = "Books and tutorials"
    url = "/books-tutorials/"
    weight = 3
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cognitive-science-stan/cognitive-science-stan.github.io"
    weight = 4


[params]
    description = "Stan for cognitive science"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

 

